version: "3"

services:
    api:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        image: counting_words:0.1
        volumes:
            - ../:/project
        ports:
            - "14000:14000"
        working_dir: /project
        command: gunicorn -c gunicorn.conf main:app
